### ISSUE TITLE
Spark Operator failin

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#21]
@LaVLaS I am seeing some errors in Spark operator:

```
sparkhistoryservers.radanalytics.io is forbidden: User "system:serviceaccount:opendatahub:spark-operator" cannot watch resource "sparkhistoryservers" in API group "radanalytics.io" at the cluster scope
```

and 

```
2020-04-06 09:08:53 INFO  SparkClusterOperator:141 - Skipping full reconciliation for namespace '*' (not supported)
```

**Comment by vpavlin** [comment]
And more...

```
CustomResourceSupport{kind='SparkCluster', apiVersion='radanalytics.io/v1', metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=2020-04-06T10:07:03Z, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=2, labels={opendatahub.io/component=jupyterhub}, managedFields=[], name=spark-vpavlin, namespace=opendatahub, ownerReferences=[], resourceVersion=8993307, selfLink=/apis/radanalytics.io/v1/namespaces/opendatahub/sparkclusters/spark-vpavlin, uid=651c93db-777a-487c-b20f-2ad39d1b4ed0, additionalProperties={})}
2020-04-06 10:20:53 INFO  AbstractWatcher:197 - modifying SparkCluster:  
spark-vpavlin

2020-04-06 10:20:53 WARN  AbstractWatcher:205 - Error when reacting on event, cause: null
java.lang.NullPointerException
	at io.radanalytics.operator.cluster.SparkClusterOperator.isOnlyScale(SparkClusterOperator.java:260)
	at io.radanalytics.operator.cluster.SparkClusterOperator.onModify(SparkClusterOperator.java:109)
	at io.radanalytics.operator.cluster.SparkClusterOperator.onModify(SparkClusterOperator.java:34)
	at io.radanalytics.operator.common.AbstractOperator.onAction(AbstractOperator.java:176)
	at io.radanalytics.operator.common.AbstractOperator.onModify(AbstractOperator.java:168)
	at io.radanalytics.operator.common.AbstractWatcher.handleAction(AbstractWatcher.java:198)
	at io.radanalytics.operator.common.AbstractWatcher.access$300(AbstractWatcher.java:29)
	at io.radanalytics.operator.common.AbstractWatcher$2.eventReceived(AbstractWatcher.java:138)
	at io.radanalytics.operator.common.AbstractWatcher$2.eventReceived(AbstractWatcher.java:127)
	at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:237)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
