### ISSUE TITLE
Grafana operator pods crashing

### ISSUE THREAD

**Issue by 4n4nd** [opendatahub-io/odh-manifests#287]
**Describe the bug**
Since this morning two of our deployments for the Grafana-operator have been crashing.
The pod logs:
```
{"level":"info","ts":1611155371.1778347,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"grafana-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1611155371.2796001,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"grafana-controller"}
{"level":"info","ts":1611155371.2797432,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"grafana-controller","worker count":1}
E0120 15:09:31.381317       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1398 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14bad20, 0x20f7ca0)
	/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x14bad20, 0x20f7ca0)
	/usr/lib/golang/src/runtime/panic.go:969 +0x175
github.com/integr8ly/grafana-operator/v3/pkg/controller/grafana.(*GrafanaReconciler).getGrafanaServiceDesiredState(0xc001007be0, 0xc001007c58, 0xc0007d5500, 0x0, 0x1)
	grafana-operator/pkg/controller/grafana/grafana_reconciler.go:112 +0xa9
github.com/integr8ly/grafana-operator/v3/pkg/controller/grafana.(*GrafanaReconciler).Reconcile(0xc001007be0, 0xc001007c58, 0xc0007d5500, 0xc0007d5500, 0x184d960, 0xc0007deab0)
	grafana-operator/pkg/controller/grafana/grafana_reconciler.go:34 +0x134
github.com/integr8ly/grafana-operator/v3/pkg/controller/grafana.(*ReconcileGrafana).Reconcile(0xc0005aea00, 0xc0007f9a30, 0xe, 0xc0007f9a20, 0x7, 0x3e2a141d9, 0xc001610000, 0xc0001b6098, 0xc0001b6090)
	grafana-operator/pkg/controller/grafana/grafana_controller.go:169 +0x29b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002603c0, 0x150daa0, 0xc000b88040, 0x0)
	/home/hstefans/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:256 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002603c0, 0x203000)
	/home/hstefans/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0002603c0)
	/home/hstefans/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000218050)
	/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000218050, 0x180a6a0, 0xc001608030, 0xc001602001, 0xc000378240)
	/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000218050, 0x3b9aca00, 0x0, 0x100000000000001, 0xc000378240)
	/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133 +0xe5
k8s.io/apimachinery/pkg/util/wait.Until(0xc000218050, 0x3b9aca00, 0xc000378240)
	/home/hstefans/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/hstefans/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:193 +0x32d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12edae9]
```
The kfdef we are using is available [here](https://github.com/operate-first/apps/blob/master/odh/base/monitoring/kfdef.yaml#L33-L49)

**Steps To Reproduce**
1. Copy [this kfdef](https://github.com/operate-first/apps/blob/master/odh/base/monitoring/kfdef.yaml#L33-L49)
2. Deploy it using the odh-operator

**Expected behavior**
pods not crash

**Workaround (if any)**
none yet

**Open Data Hub Version**
Relevant [kfdef](https://github.com/operate-first/apps/blob/master/odh/base/monitoring/kfdef.yaml#L33-L49)

**OpenShift Version**
Version #: v4.5
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): n/a

**Additional context**n/a

**Comment by 4n4nd** [comment]
this might be an issue with the upstream grafana-operator: https://github.com/integr8ly/grafana-operator/pull/334
