### ISSUE TITLE
Facing "500: Internal Server Error" while logging into JupyterHub

### ISSUE THREAD

**Issue by Harshit-9398** [opendatahub-io/odh-manifests#319]
Hello,  
I am trying to run JupyterHub deployed using the **Open Data Hub v1.0.0** but I am facing `500: Internal Server Error` when I am logging into the JupyterHub.
I have tested this both on my **OpenShift cluster** as well as on **Katacoda**. Instead of the **Spawner Page**, this error shows up just after authenticating in the JupyterHub pod.

![JH-1-error](https://user-images.githubusercontent.com/36565937/108197744-cc0a3a00-7140-11eb-9116-b477d53fd5fd.png)

Below are the logs of JupyterHub pod running on Katacoda for your reference:
```log
11:49:11.481 [ConfigProxy] [32minfo[39m: 200 GET /api/routes 
11:49:16.496 [ConfigProxy] [32minfo[39m: 200 GET /api/routes 
[D 2021-02-17 11:49:18.113 JupyterHub app:2000] Managed service jsp-api running at http://127.0.0.1:8181
[D 2021-02-17 11:49:18.930 JupyterHub base:1280] No template for 405
[W 2021-02-17 11:49:18.932 JupyterHub log:181] 405 HEAD / (@::ffff:10.116.0.1) 3.70ms
[W 2021-02-17 11:49:18.977 JupyterHub iostream:1407] SSL Error on 15 ('35.201.124.219', 443): [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
[E 2021-02-17 11:49:18.978 JupyterHub web:1793] Uncaught exception GET /hub/oauth_callback?code=vr2vZZIOH_fSABo39vEJw3kQARf7UHzlhMlrQv-qMGg&state=eyJzdGF0ZV9pZCI6ICJiODdhYzMyYjI5YWY0OWMwOGYxNjFjNmE4NWNlODlhNyIsICJuZXh0X3VybCI6ICIvaHViLyJ9 (35.186.156.29)
    HTTPServerRequest(protocol='http', host='jupyterhub-odh-1-test.2886795285-80-host19nc.environments.katacoda.com', method='GET', uri='/hub/oauth_callback?code=vr2vZZIOH_fSABo39vEJw3kQARf7UHzlhMlrQv-qMGg&state=eyJzdGF0ZV9pZCI6ICJiODdhYzMyYjI5YWY0OWMwOGYxNjFjNmE4NWNlODlhNyIsICJuZXh0X3VybCI6ICIvaHViLyJ9', version='HTTP/1.1', remote_ip='35.186.156.29')
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/app-root/lib/python3.6/site-packages/oauthenticator/oauth2.py", line 224, in get
        user = await self.login_user()
      File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/handlers/base.py", line 749, in login_user
        authenticated = await self.authenticate(data)
      File "/opt/app-root/lib/python3.6/site-packages/jupyterhub/auth.py", line 462, in get_authenticated_user
        authenticated = await maybe_future(self.authenticate(handler, data))
      File "/opt/app-root/lib/python3.6/site-packages/oauthenticator/openshift.py", line 108, in authenticate
        resp = await http_client.fetch(req)
      File "/opt/app-root/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 344, in run
        source_ip=source_ip,
      File "/opt/app-root/lib/python3.6/site-packages/tornado/tcpclient.py", line 289, in connect
        False, ssl_options=ssl_options, server_hostname=host
      File "/opt/app-root/lib/python3.6/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake
        self.socket.do_handshake()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 1077, in do_handshake
        self._sslobj.do_handshake()
      File "/opt/rh/rh-python36/root/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
    
[D 2021-02-17 11:49:18.986 JupyterHub base:1280] No template for 500
[E 2021-02-17 11:49:18.990 JupyterHub log:173] {
      "Forwarded": "for=172.17.0.2;host=jupyterhub-odh-1-test.2886795285-80-host19nc.environments.katacoda.com;proto=https",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "jupyterhub-odh-1-test.2886795285-80-host19nc.environments.katacoda.com",
      "Host": "jupyterhub-odh-1-test.2886795285-80-host19nc.environments.katacoda.com",
      "Accept-Encoding": "gzip",
      "X-Real-Ip": "35.186.156.29",
      "X-Katacoda-Host": "host19nc",
      "X-Forwarded-For": "157.38.15.0, 35.201.124.219, 130.211.2.183, 35.186.156.29, 172.17.0.7, 172.17.0.2,::ffff:10.116.0.1",
      "X-Cloud-Trace-Context": "a69f53cb5f128023e319a25711829822/5191074374450044905",
      "X-Client-Data": "CgSM6ZsV",
      "Via": "1.1 google",
      "Upgrade-Insecure-Requests": "1",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "same-site",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Dest": "document",
      "Referer": "https://oauth-openshift-2886795285-443-host19nc.environments.katacoda.com/",
      "Dnt": "1",
      "Cookie": "oauthenticator-state=[secret]",
      "Cache-Control": "max-age=0",
      "Accept-Language": "en-US,en;q=0.9,hi;q=0.8",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36",
      "Connection": "close"
    }
[E 2021-02-17 11:49:18.990 JupyterHub log:181] 500 GET /hub/oauth_callback?code=[secret]&state=[secret] (@35.186.156.29) 40.54ms
[D 2021-02-17 11:49:19.822 JupyterHub base:1280] No template for 405
[W 2021-02-17 11:49:19.824 JupyterHub log:181] 405 HEAD / (@::ffff:10.116.0.1) 2.71ms
[D 2021-02-17 11:49:19.832 JupyterHub base:1280] No template for 405
[W 2021-02-17 11:49:19.834 JupyterHub log:181] 405 HEAD / (@::ffff:10.116.0.1) 3.11ms
[D 2021-02-17 11:49:19.846 JupyterHub log:181] 200 GET /hub/static/components/bootstrap/dist/js/bootstrap.min.js?v=a014e9acc78d10a0a7a9fbaa29deac6ef17398542d9574b77b40bf446155d210fa43384757e3837da41b025998ebfab4b9b6f094033f9c226392b800df068bce (@35.186.156.29) 2.35ms
[D 2021-02-17 11:49:19.851 JupyterHub base:1280] No template for 405
[W 2021-02-17 11:49:19.853 JupyterHub log:181] 405 HEAD / (@::ffff:10.116.0.1) 5.53ms
[D 2021-02-17 11:49:19.855 JupyterHub base:1280] No template for 405
[W 2021-02-17 11:49:19.858 JupyterHub log:181] 405 HEAD / (@::ffff:10.116.0.1) 8.16ms
[D 2021-02-17 11:49:19.861 JupyterHub log:181] 200 GET /hub/static/components/jquery/dist/jquery.min.js?v=6cb4f4426f559c06190df97229c05a436820d21498350ac9f118a5625758435171418a022ed523bae46e668f9f8ea871feab6aff58ad2740b67a30f196d65516 (@35.186.156.29) 1.63ms
[D 2021-02-17 11:49:19.870 JupyterHub log:181] 200 GET /hub/static/components/requirejs/require.js?v=bd1aa102bdb0b27fbf712b32cfcd29b016c272acf3d864ee8469376eaddd032cadcf827ff17c05a8c8e20061418fe58cf79947049f5c0dff3b4f73fcc8cad8ec (@35.186.156.29) 2.44ms
[D 2021-02-17 11:49:19.875 JupyterHub log:181] 200 GET /hub/static/css/style.min.css?v=a690a7f26f8eda24b6043d972eda379b7f3df65dcb4832fbec0d72d1585b6bdf2bd15c7f3ec4597b79a7c91798181ba23b9a0204da8165b21ff81cd85f89a933 (@35.186.156.29) 2.55ms
[D 2021-02-17 11:49:21.274 JupyterHub base:1280] No template for 405
[W 2021-02-17 11:49:21.276 JupyterHub log:181] 405 HEAD / (@::ffff:10.116.0.1) 3.82ms
[D 2021-02-17 11:49:21.290 JupyterHub log:181] 200 GET /hub/logo (@35.186.156.29) 1.91ms
11:49:21.506 [ConfigProxy] [32minfo[39m: 200 GET /api/routes 
```

Can you please tell me if I am doing something wrong, or is it actually an issue in the new release?

**Comment by Harshit-9398** [comment]
Hey,  
Is there any update on this?

**Comment by nakfour** [comment]
@Harshit-9398 this seems to be happening on clusters with self certified certificates, can you try and pull the manifest from master, just add it to the uri field.

**Comment by Harshit-9398** [comment]
Hey @nakfour,  
Thanks for the update, I have tried the way you suggested and it is working fine for me now.  
I have one more query, can you please tell me where can I find the source code of the JupyterHub UI, so that I am able to make some customizations in the UI according to my use case.

**Comment by mroman-redhat** [comment]
@Harshit-9398 If you mean the Spawner UI, the source code is here: https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/tree/master/jupyterhub_singleuser_profiles/ui

**Comment by stobias123** [comment]
I'm running into this same issue. Using letsencrypt certs on my ingress. 

What was the resolution here? I'm not sure I follow.

**Comment by nakfour** [comment]
@stobias123 try changing the uri in your kfdef to point to master to pull the new code that has a fix.
