### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by Sg-23** [opendatahub-io/odh-manifests#434]
I'm facing issue while starting jupyterhub. I'm getting 500 Internal server error and the below error in logs of jupyterhub pod:

Traceback (most recent call last):
  File "/opt/app-root/bin/jupyterhub-singleuser-profiles-api", line 5, in <module>
    from jupyterhub_singleuser_profiles.api.api import main
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/api/api.py", line 19, in <module>
    _PROFILES = SingleuserProfiles(verify_ssl=False)
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/profiles.py", line 37, in __init__
    self.user = User(self.openshift, default_image=self.images.get_default())
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/images.py", line 40, in get_default
    image_list, code = self.get(detailed=False)
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/images.py", line 106, in get
    self.append_option(i, images)
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/images.py", line 91, in append_option
    if not self.tag_exists(tag.tag, image):
  File "/opt/app-root/lib/python3.6/site-packages/jupyterhub_singleuser_profiles/images.py", line 48, in tag_exists
    for tag in imagestream.spec.tags:
TypeError: 'NoneType' object is not iterable
[W 2021-06-03 18:25:04.650 JupyterHub app:2106] Cannot connect to managed service jsp-api at http://127.0.0.1:8181

**Comment by nakfour** [comment]
@Sg-23 what is the openshift version you are running ODH on? Also how did you install ODH?

**Comment by LaVLaS** [comment]
@Sg-23 This issue will be resolved when JupyterHub is updated to v0.3.0 in #435
